name: component-operator-management
repoURL: https://github.com/entr0pian/component-operator.git
chart: ""
chartPath: chart
targetRevision: "1b173a033965e4b1283675bd393abcf3f3ba29aa"
namespace: component-operator-system
createNamespace: true
serverSideApply: true
wave: "3"
notify: true
values: ""
