name: schema-operator-management
repoURL: https://github.com/entr0pian/schema-operator.git
chart: ""
chartPath: chart
targetRevision: "12c347e4bf61aa5a683df30a1ce03314f742908e"
namespace: schema-operator-system
createNamespace: true
serverSideApply: true
wave: "3"
notify: true
values: ""
