name: scaffold-operator-management
repoURL: https://github.com/entr0pian/scaffold-operator.git
chart: ""
chartPath: chart
targetRevision: "87e862b4fe3ffbbedfe6951776bc821a4ac7a208"
namespace: scaffold-operator-system
createNamespace: true
serverSideApply: true
wave: "3"
notify: true
values: ""
