name: scaffold-operator-management
repoURL: https://github.com/entr0pian/scaffold-operator.git
chart: ""
chartPath: chart
targetRevision: "0db13c9119798e27b0f26dbac545c28f6aa69c38"
namespace: scaffold-operator-system
createNamespace: true
serverSideApply: true
wave: "3"
notify: true
values: ""
