name: release-operator-management
repoURL: https://github.com/entr0pian/release-operator.git
chart: ""
chartPath: chart
targetRevision: "064a41d2d1098d85ec229ec4f478404bc8451542"
namespace: release-operator-system
createNamespace: true
serverSideApply: true
wave: "3"
notify: true
values: ""
