name: crossplane-provider-config-management
repoURL: https://github.com/entr0pian/helm-charts.git
chart: ""
chartPath: crossplane-provider-config
targetRevision: main
namespace: crossplane-system
createNamespace: true
serverSideApply: false
wave: "2"
notify: true
values: ""
