name: traffic-generator-prod
values: |
  targets:
    - name: payments
      url: http://payments.prod.svc.cluster.local:8080
      minRate: 1
      maxRate: 20
      spikeChance: 0.15
      requests:
        - path: /
          weight: 9
        - path: /does-not-exist
          weight: 1
    - name: checkout
      url: http://checkout.prod.svc.cluster.local:8080
      minRate: 1
      maxRate: 10
      spikeChance: 0.15
      requests:
        - path: /
          weight: 9
        - path: /does-not-exist
          weight: 1
