apiVersion: platform.taskapp.io/v1alpha1
kind: ApplicationRepository
metadata:
  name: backend
spec:
  repoURL: https://github.com/entr0pian/backend.git
  targetRevision: main
  chartPath: chart
  clusters:
    - name: dev
      namespace: default
      imageTag: "c3f5e94f23e798b460d8c9811a7fd0976913cc45"