name: backstage-management
repoURL: https://github.com/entr0pian/backstage.git
chart: ""
chartPath: chart
targetRevision: "7e71bd6df102eace8a3c9a7d3f591471f11723c9"
namespace: backstage
createNamespace: true
serverSideApply: true
wave: "3"
notify: true
values: ""
