name: backstage-management
repoURL: https://github.com/entr0pian/backstage.git
chart: ""
chartPath: chart
targetRevision: "6285cfcbee4956912674fa8b598fca70224d3345"
namespace: backstage
createNamespace: true
serverSideApply: true
wave: "3"
notify: true
values: ""
