name: backstage-management
repoURL: https://github.com/entr0pian/backstage.git
chart: ""
chartPath: chart
targetRevision: "611807f44d74dd8fa8de59adbcaf2ef703ef2d42"
namespace: backstage
createNamespace: true
serverSideApply: true
wave: "3"
notify: true
values: ""
