name: kube-prometheus-stack-dev
repoURL: https://prometheus-community.github.io/helm-charts
chart: kube-prometheus-stack
chartPath: ""
targetRevision: "84.4.0"
namespace: monitoring
createNamespace: true
serverSideApply: true
wave: "0"
notify: false
values: ""
