apiVersion: platform.taskapp.io/v1alpha1
kind: Release
metadata:
  name: checkout-management
  labels:
    platform.taskapp.io/component: checkout
spec:
  componentRef:
    name: checkout
  environment: management
  version: "ca56209c47cc0393d395d3b93e69d99eb01502ba"
