apiVersion: platform.taskapp.io/v1alpha1
kind: Release
metadata:
  name: checkout-management
  labels:
    platform.taskapp.io/component: checkout
spec:
  componentRef:
    name: checkout
  environment: management
  version: "f3f4dbb1de81550cffcfc7904fc948f77fa73f1f"
  bindings:
    database:
      enabled: true
      ref: checkout-db
