apiVersion: platform.taskapp.io/v1alpha1
kind: Release
metadata:
  name: payments-management
  labels:
    platform.taskapp.io/component: payments
spec:
  componentRef:
    name: payments
  environment: management
  version: "f39bf9eb0dcea430b0aa491abd2966970ae728b1"
  bindings:
    database:
      enabled: true
      ref: payments-db
