apiVersion: platform.taskapp.io/v1alpha1
kind: Release
metadata:
  name: checkout-dev
  labels:
    platform.taskapp.io/component: checkout
spec:
  componentRef:
    name: checkout
  environment: dev
  version: "458170d82e33a34b8e92c93cf1cfd8e6dacf85ac"
  autoDeploy:
    branch: main
