apiVersion: platform.taskapp.io/v1alpha1
kind: Release
metadata:
  name: checkout-dev
  labels:
    platform.taskapp.io/component: checkout
spec:
  componentRef:
    name: checkout
  environment: dev
  version: "05ae2aef54d01c0e5ddbe7fbd1f8cd8f506e81ef"
  autoDeploy:
    branch: main
