apiVersion: platform.taskapp.io/v1alpha1
kind: DatabaseSchema
metadata:
  name: payments
  labels:
    platform.taskapp.io/component: payments
spec:
  componentRef:
    name: payments
  version: "54f3f80a9a9e8b3dfe78bd95fad3cd0a0f6d14e4"
