apiVersion: platform.taskapp.io/v1alpha1
kind: Release
metadata:
  name: payments-dev
  labels:
    platform.taskapp.io/component: payments
spec:
  componentRef:
    name: payments
  environment: dev
  version: "9f48bf49efe8dec2d6c7cd83f85815f6f9223aec"
  autoDeploy:
    branch: main
  bindings:
    database:
      enabled: true
      ref: payments-db
