apiVersion: platform.taskapp.io/v1alpha1
kind: Release
metadata:
  name: payments-dev
  labels:
    platform.taskapp.io/component: payments
spec:
  componentRef:
    name: payments
  environment: dev
  version: "6a4d1879aaaf56b7af7e45ca775470999f427f3a"
