name: platform-prod
values: |
  limitRange:
    enabled: true
  prometheusRules:
    enabled: true
  grafanaDashboard:
    enabled: true
  crossplane:
    secretPath: ""
  argocdWriteToken:
    secretPath: ""
  crossplaneGithub:
    secretPath: ""
