# Written by schema-operator from a DatabaseSchema. Don't edit by hand:
# change the DatabaseSchema in platform/environments/ instead.
chart: schema
commit: 9f48bf49efe8dec2d6c7cd83f85815f6f9223aec
component: payments
database:
  name: payments-db
  remoteRef: /bindings/dev/databases/payments-db
environment: dev
namespace: dev
repoURL: ghcr.io/entr0pian/payments
version: 0.0.0-g9f48bf49efe8dec2d6c7cd83f85815f6f9223aec
