# Written by schema-operator from a DatabaseSchema. Don't edit by hand:
# change the DatabaseSchema in platform/environments/ instead.
chart: schema
commit: 4b63400b4954661d5a3f25dcf5caa8b990c97bcd
component: payments
database:
  name: payments-db
  remoteRef: /bindings/dev/databases/payments-db
environment: dev
namespace: dev
repoURL: ghcr.io/entr0pian/payments
version: 0.0.0-g4b63400b4954661d5a3f25dcf5caa8b990c97bcd
